version: '3.4'
services:
  db:
    image: postgres:14.8
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=si1
      - POSTGRES_USER=alumnodb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./dump_p2_v1.sql.gz:/docker-entrypoint-initdb.d/1_data.sql.gz
      - ./scripts/actualiza.sql:/actualiza.sql
      - ./scripts/actualizaPrecios.sql:/actualizaPrecios.sql
      - ./scripts/actualizaTablas.sql:/actualizaTablas.sql
      - ./scripts/actualizaCarrito.sql:/actualizaCarrito.sql
      - ./scripts/pagado.sql:/pagado.sql
      - ./scripts/actualizaPreciosPedidos.sql:/actualizaPreciosPedidos.sql
  
  
  db_v2:
    image: postgres:14.8
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=si2
      - POSTGRES_USER=alumnodb
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./dump_p2_v2.sql.gz:/docker-entrypoint-initdb.d/2_data.sql.gz
 
